AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  light-measure

  Sample SAM Template for light-measure

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LightMeasurementsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: LightMeasurements
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: year
          AttributeType: N
        - AttributeName: month
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: YearMonthIndex
          KeySchema:
            - AttributeName: year
              KeyType: HASH
            - AttributeName: month
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  CreateMeasurementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers
      Handler: createMeasure.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref LightMeasurementsTable
          INDEX_NAME: YearMonthIndex

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LightMeasurementsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /measure
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - createMeasure.ts

  GetMeasurementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers
      Handler: getMeasure.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref LightMeasurementsTable
          INDEX_NAME: YearMonthIndex

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LightMeasurementsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /measure/{id}
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - getMeasure.ts

  UpdateMeasurementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers
      Handler: updateMeasure.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref LightMeasurementsTable
          INDEX_NAME: YearMonthIndex

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LightMeasurementsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /measure/{id}
            Method: PUT
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - updateMeasure.ts

  DeleteMeasurementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers
      Handler: deleteMeasure.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref LightMeasurementsTable
          INDEX_NAME: YearMonthIndex

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LightMeasurementsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /measure/{id}
            Method: DELETE
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - deleteMeasure.ts

  SearchMeasurementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers
      Handler: searchMeasure.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref LightMeasurementsTable
          INDEX_NAME: YearMonthIndex

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LightMeasurementsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /measure/search
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - searchMeasure.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LightMeasurementApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/measure/"
