AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  light-measure

  Sample SAM Template for light-measure

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Stage:
    Type: String
    Default: dev

Resources:
  LightMeasurementsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: LightMeasurements
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: year
          AttributeType: N
        - AttributeName: month
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: YearMonthIndex
          KeySchema:
            - AttributeName: year
              KeyType: HASH
            - AttributeName: month
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  LightMeasurementApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
        AllowHeaders: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
        AllowCredentials: true

  CreateMeasurementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers/createMeasure.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref LightMeasurementsTable
          INDEX_NAME: YearMonthIndex
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LightMeasurementsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref LightMeasurementApi
            Path: /measure
            Method: POST

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - handlers/createMeasure.ts

  GetMeasurementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers/getMeasure.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref LightMeasurementsTable
          INDEX_NAME: YearMonthIndex
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LightMeasurementsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref LightMeasurementApi
            Path: /measure/{id}
            Method: GET

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - handlers/getMeasure.ts

  UpdateMeasurementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers/updateMeasure.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref LightMeasurementsTable
          INDEX_NAME: YearMonthIndex

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LightMeasurementsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref LightMeasurementApi
            Path: /measure/{id}
            Method: PUT

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - handlers/updateMeasure.ts

  DeleteMeasurementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers/deleteMeasure.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref LightMeasurementsTable
          INDEX_NAME: YearMonthIndex

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LightMeasurementsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref LightMeasurementApi
            Path: /measure/{id}
            Method: DELETE

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - handlers/deleteMeasure.ts

  SearchMeasurementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers/searchMeasure.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref LightMeasurementsTable
          INDEX_NAME: YearMonthIndex

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LightMeasurementsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref LightMeasurementApi
            Path: /measure/search
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - handlers/searchMeasure.ts

Outputs:
  LightMeasurementApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${LightMeasurementApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/measure/"
  CreateMeasurementFunction:
    Description: "CreateMeasurementFunction ARN"
    Value: !GetAtt CreateMeasurementFunction.Arn
  GetMeasurementFunction:
    Description: "GetMeasurementFunction ARN"
    Value: !GetAtt GetMeasurementFunction.Arn
  UpdateMeasurementFunction:
    Description: "UpdateMeasurementFunction ARN"
    Value: !GetAtt UpdateMeasurementFunction.Arn
  DeleteMeasurementFunction:
    Description: "DeleteMeasurementFunction ARN"
    Value: !GetAtt DeleteMeasurementFunction.Arn
  SearchMeasurementFunction:
    Description: "SearchMeasurementFunction ARN"
    Value: !GetAtt SearchMeasurementFunction.Arn
